export default function() {
  return {
    formData: {
      filterFileItems: [],
      filterItems: [],
      items: [],
      objectItems: [],
      changeList: [],
      contactItems: [],
      fileItems: [],
      pkId: null,
      poNo: "",
      poDate: null,
      signSite: "",
      prmyScny: "C",
      orderId: null,
      vendorId: null,
      vendorNo: "",
      validTo: null,
      dlvTerm: "",
      payTerm: "",
      payMode: "",
      prepayDate: null,
      prepayPortion: null,
      prepaySum: null,
      payDetail: "",
      currencyCode: "CNY",
      exchRate: null,
      payDate: null,
      shipTo: "",
      shipVia: "",
      msd: null,
      partialShip: "N",
      earlyShip: "N",
      notifyDays: null,
      needInspect: "Y",
      totalPoValue: 0,
      totalPoValueS: 0,
      poDocNo: "",
      lglTerm: "",
      managerId: null,
      mConfirmDate: null,
      auditStatus: "D",
      auditDate: null,
      vConfirmDate: null,
      rcvComfirmDate: null,
      poStatus: "U",
      vProposalRefNo: "",
      refNo: "",
      control1: null,
      control2: null,
      remark: "",
      employeeId: 0,
      groupId: 0,
      deptId: 0,
      cfmPerson: "",
      cfmTitle: "",
      cmfSite: "",
      cfmComment: "",
      titleName: "",
      refNoTitle1: "",
      refNoTitle2: "",
      refNoTitle3: "",
      ordTypNo: "",
      orderType: "",
      objectNo: "",
      orderNo: "",
      contractNo: "",
      currencyCode1: null,
      exchRate1: null,
      empid: 0,
      vendorName: "",
      payAmount: 0,
      payflag: null,
      latShipDate: null,
      rkFlag: null,
      soType: null,
      contractType: "",
      signDate: null,
      ysDate: null,
      mDeptId: null,
      mEmpId: null,
      totalQuantity: 0,
      invFlag: null,
      payFlag1: null,
      invFlag1: null,
      rkFlag1: null,
      orgCoNo: "",
      orgNo: "",
      mOrgNo: "",
      employeeNo: "",
      empNo: "",
      mEmpNo: "",
      auditorNo: "",
      acctorNo: "",
      docVersion: 1.0,
      currentVersion: 0,
      versionDate: null,
      docEntry: "",
      LType: null,
      jsType: null,
      jhType: null,
      rkFlag2: null,
      rkFlag3: null,
      effectFlag: 0,
      effectDate: null,
      effecteMemo: null,
      effectEmpNo: null,
      orderMode: "",
      offlineaudit: null,
      wareLocNo: "",
      wareLoc: "",
      rkAmount: 0,
      rkAmount1: 0,
      docEntry1: null,
      invSl: null,
      invAmount: null,
      payDate1: null,
      poType: null,
      baseSource: null,
      quatity: null,
      quatityPeriod: null,
      delivery: null,
      transAndFee: null,
      settlement: null,
      rkSl: null,
      lastAuditStatus: null,
      orgName: null,
      employeeName: "",
      empName: "",
      sapType: "",
      sapOrderNo: "",
      sapCreateDate: null,
      onlineOk: "",
      printOk: ""
    },
    baseDetail: {
      pkid: null,
      poProductId: null,
      poNo: "",
      pdtId: null,
      pdtNo1: "",
      prodNo: "",
      vProdNo: "",
      prodName: "",
      prodDescript: "",
      packType: "",
      packDescript: "",
      specification: "",
      shipMark: "",
      lotNo: "",
      serialNo: null,
      uom: "",
      unitStdCost: 0,
      unitStdCostS: 0,
      amountPs: 1,
      uom1: "",
      quantity: 0,
      subSumValue: 0,
      subSumValueS: 0,
      volume: "",
      volumeUom: "",
      grossWeight: 0,
      netWeight: 0,
      weightUom: "",
      subSumVolume: 0,
      remark: "",
      vProdId: 0,
      cmpsFlag: "",
      cmpsPrnt: "",
      uintPrice: 0,
      uintPriceA: 0,
      subPrice: 0,
      subPriceA: 0,
      expVolume1: "",
      sizeSpec: "",
      labeling: "",
      userCommit: "",
      feetotal: 0,
      reqCost: 0,
      reqPrice: 0,
      reqQuantity: 0,
      expWeight: "",
      weightRate: "",
      volumeRate: "",
      dtrA: 0,
      dtrC: 0,
      atr: 0,
      trC: 0,
      trCst: 0,
      licensFee: "",
      licensQtty: "",
      discountRate: "",
      oreintPrice: "",
      piece: 0,
      overage: 0,
      shortage: 0,
      pManuFactory: "",
      shipmentDate: null,
      refNo1: null,
      refNo2: null,
      refNo3: null,
      specId: null,
      rkFlag: 0,
      rkSl: 0,
      rkSl1: 0,
      rkChSl: 0,
      rkChSl1: 0,
      ydSl: 0,
      ydSl1: 0,
      bhSl: 0,
      ztSl: 0,
      kydSl: 0,
      krkSl: 0,
      dyzSl: 0,
      execSl: 0,
      execSl1: 0,
      empId: 0,
      deptId: 0,
      orderTypeNo: "",
      auditStatus: "D",
      isOrderMid: null,
      isNo: null,
      orderSid: null,
      orderNo: null,
      execFlag: 0,
      bhsDj: null,
      hsDj: null,
      otherTaxRate: null,
      pdtNameE: "",
      deliverPort: null,
      deliverDate: null,
      wareHsId: null,
      wareHsMid: null,
      soType: "0",
      vendorNo: "",
      vendorName: "",
      remark1: null,
      docEntry: "",
      wareLocNo: "",
      wareLoc: "",
      originalCountry: null,
      qualityLevel: null,
      rkAmount: null,
      quantity1: null,
      rkAmount1: null,
      rkDate: null,
      orderMid1: 0,
      orderMid2: 0,
      changeFlag1: 0,
      changeFlag2: 0,
      fee: null,
      flag1: 0,
      flag2: 1,
      invFlag: 0,
      invSl: null,
      invAmount: null,
      contractNo: null,
      pdtCodeC: null,
      reqMid: null,
      baseSource: null,
      ckQnt: null,
      ckAmnt: null,
      hxSl: null,
      hxAmount: null,
      hxAmountNt: null,
      hxFlag: 0,
      custNo: null,
      custName: null,
      employeeNo: "",
      orgNo: "",
      salUnit: null,
      packUnit: null,
      volumeSum: null,
      netWeighSum: null,
      grossWeighSum: null,
      amountPs1: null,
      hl: null,
      sapEbelp: null,
      sapOrderNo: "",
      sapUnit: null,
      sapUnitRate: null,
      sapPrice: null,
      sapQtty: null,
      uomName: ""
    },
    // baseDetail: {
    //   amount: null,
    //   amountPs: null,
    //   atr: null,//增值税率(%)
    //   cartons: null,
    //   changeFlag1: null,
    //   changeFlag2: null,
    //   ckAmount: null,
    //   ckAmount1: null,
    //   ckFlag: null,
    //   docentry: null,
    //   empid1: null,
    //   empid2: null,
    //   fee: null,
    //   flag1: null,
    //   flag2: null,
    //   flag3: null,
    //   flag4: null,
    //   groupNo: null,//组号
    //   hl: null,
    //   isMid: null,
    //   isno: "",
    //   objectNo: "",
    //   orderMid1: null,
    //   orderMid2: null,
    //   orderMidSource: null,
    //   orderNo: "",
    //   orderSid: null,
    //   originalCountry: "",
    //   overage: null,//溢装(%)
    //   pManufactory: "",
    //   pdtId: null,
    //   pdtNameC: "",
    //   pdtNameE: "",//英文品名
    //   pdtNo1: "",
    //   pkId: null,
    //   poPdtId: null,
    //   qualityLevel: "",
    //   quantity: null,
    //   quantity1: null,
    //   quantity2: null,
    //   quantity3: null,
    //   quantity4: null,
    //   remark: "",
    //   reqCost: null,
    //   reqPrice: null,
    //   reqQuantity: null,
    //   saleType: "",
    //   sapOrderNo: "",
    //   sapPosNr: "",
    //   shortage: null,//短装(%)
    //   spec: "",
    //   unitPrice: null,
    //   unitStdCost: null,
    //   uom: "",
    //   uom1: "",
    //   wareLoc: "",
    //   wareLocNo: "",
    //   sapUnit: "",
    //   sapUnitRate: "",
    //   sapPrice: null,
    //   sapQtty: null,
    // },
    // contactForm: {
    //   addr: "",
    //   addrE: "",
    //   bp: "",
    //   city: "",
    //   cityE: "",
    //   coName: "",
    //   coNameE: "",
    //   contInfoId: null,
    //   contact: "",
    //   contactE: "",
    //   controlA: "",
    //   controlB: "",
    //   country: "",
    //   countryE: "",
    //   deptName: "",
    //   deptNameE: "",
    //   docEntry: null,
    //   email: "",
    //   fax: "",
    //   isContactInfoId: null,
    //   isno: "",
    //   phone: "",
    //   state: "",
    //   stateE: "",
    //   title: "",
    //   titleE: "",
    //   zipCode: ""
    // },
    contactForm: {
      poContactInfoId: null,
      poNo: null,
      contInfoId: null,
      coName: "",
      country: "",
      state: "",
      city: "",
      deptName: "",
      contact: "",
      title: "",
      zipCode: "",
      phone: "",
      fax: "",
      email: "",
      bp: "",
      addr: "",
      controlA: "",
      controlB: "",
      docEntry: null,
      baseSource: null,
      printMan: "",
      printPhone: "",
      printId: ""
    },
    clientContactForm: {
      poContactInfoId: null,
      poNo: null,
      contInfoId: null,
      coName: "",
      country: "",
      state: "",
      city: "",
      deptName: "",
      contact: "",
      title: "",
      zipCode: "",
      phone: "",
      fax: "",
      email: "",
      bp: "",
      addr: "",
      controlA: "",
      controlB: "",
      docEntry: null,
      baseSource: null,
      printMan: "",
      printPhone: "",
      printId: ""
    },
    // clientContactForm: {
    //   addr: "",
    //   addrE: "",
    //   bp: "",
    //   city: "",
    //   cityE: "",
    //   coName: "",
    //   coNameE: "",
    //   contInfoId: null,
    //   contact: "",
    //   contactE: "",
    //   controlA: "",
    //   controlB: "",
    //   country: "",
    //   countryE: "",
    //   deptName: "",
    //   deptNameE: "",
    //   docEntry: null,
    //   email: "",
    //   fax: "",
    //   isContactInfoId: null,
    //   isno: "",
    //   phone: "",
    //   state: "",
    //   stateE: "",
    //   title: "",
    //   titleE: "",
    //   zipCode: ""
    // },
    fileItems: {
      cancelDate: "",
      empName: "",
      empNo: "",
      fileDesc: "",
      fileInfo: "",
      fileName: "",
      flag1: null,
      flag2: null,
      flag3: null,
      flag4: null,
      impDate: "",
      objId: null,
      objNo: "",
      objType: "",
      objectNo: "",
      pkId: null,
      rowId: null,
      type: "",
      webUuid: ""
    },
    filterForm: {
      post: "",
      itemType: ""
    },
    changeItems: {
      auditDate: "",
      auditStatus: "",
      auditoNo: "",
      currentersion: null,
      docEntry: null,
      docEntry1: null,
      docNo: "",
      docVersion: null,
      empNo: "",
      isNo: "",
      orgCoNo: "",
      pkId: null,
      versionDate: ""
    },
    constAnalysisForm: {
      totalIsValue: null,
      preSum: null,
      isCdAmount: null,
      poAmount: null,
      poPreAmount: null,
      poCdAmount: null,
      poPeriod: null,
      taxAmount: null,
      profit: null,
      profitRate: null,
      refNoTitle2: ""
    }
  };
}
